# Generated by Django 5.2.5 on 2026-10-04 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_last_otp_verified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_2fa_days',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='user',
            name='login_2fa_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_2fa_mode',
            field=models.CharField(choices=[('every_login', 'Every login'), ('interval', 'Every N days'), ('inactivity', 'After inactivity')], default='interval', max_length=20),
        ),
    ]
