"""
Django settings for kodehax_academy project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import ssl
import importlib.util
from pathlib import Path
from django.core.exceptions import ImproperlyConfigured


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file():
    env_candidates = (
        BASE_DIR.parent / ".env",
        BASE_DIR / ".env",
    )
    for env_path in env_candidates:
        if not env_path.exists():
            continue
        for line in env_path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, value = line.split("=", 1)
            os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))
        break


_load_env_file()


PRODUCTION = os.getenv("PRODUCTION", "False").lower() == "true"


def _env_bool(name, default=False):
    return os.getenv(name, str(default)).lower() == "true"


def _env_list(name, default=""):
    return [item.strip() for item in os.getenv(name, default).split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "")
if not SECRET_KEY:
    if PRODUCTION:
        raise ImproperlyConfigured("SECRET_KEY must be set in production.")
    SECRET_KEY = "django-insecure-dev-only-change-me"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DEBUG", False)
if PRODUCTION and DEBUG:
    raise ImproperlyConfigured("DEBUG must be False in production.")

ALLOWED_HOSTS = _env_list("ALLOWED_HOSTS", "" if PRODUCTION else "localhost,127.0.0.1")
if not PRODUCTION and not ALLOWED_HOSTS and not DEBUG:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
if PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured("ALLOWED_HOSTS must be set in production.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'users',
    'student',
    'teacher',
    'adminpanel',
    'skill_assessment',
    'daily_challenges',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'kodehax_academy.middleware.DeviceDetectionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'adminpanel.middleware.MaintenanceModeMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if importlib.util.find_spec("whitenoise"):
    MIDDLEWARE.insert(1, 'whitenoise.middleware.WhiteNoiseMiddleware')

ROOT_URLCONF = 'kodehax_academy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'teacher.context_processors.teacher_profile_nav',
                'student.context_processors.student_nav_context',
            ],
            'libraries': {
                'breadcrumbs': 'users.templatetags.breadcrumbs',
            },
        },
    },
]

WSGI_APPLICATION = 'kodehax_academy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Development and production use the same existing MySQL database configuration.
# SQLite is explicitly overridden only in test_settings.py.
if PRODUCTION:
    missing = [name for name in ("DB_NAME", "DB_USER", "DB_PASSWORD", "DB_HOST", "DB_PORT")
               if not os.getenv(name)]
    if missing:
        raise ImproperlyConfigured("Missing production database variables: " + ", ".join(missing))

_db_options = {"charset": "utf8mb4"}
if _env_bool("DB_SSL_REQUIRED") or os.getenv("DB_SSL_CA"):
    # Require encryption, a trusted certificate chain, and a matching hostname.
    if os.getenv("DB_SSL_CA") and not Path(os.environ["DB_SSL_CA"]).is_file():
        raise ImproperlyConfigured("DB_SSL_CA must point to a readable CA certificate file.")
    _db_options["ssl"] = ssl.create_default_context(cafile=os.getenv("DB_SSL_CA") or None)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("DB_NAME", "kodehax_academy"),
        "USER": os.getenv("DB_USER", "root"),
        "PASSWORD": os.getenv("DB_PASSWORD", ""),
        "HOST": os.getenv("DB_HOST", "localhost"),
        "PORT": os.getenv("DB_PORT", "3306"),
        "OPTIONS": _db_options,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'accounts.validators.StrongPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv("TIME_ZONE", "Asia/Kolkata")

USE_I18N = True

USE_TZ = True

DAILY_CHALLENGE_TIMEZONE = os.getenv("DAILY_CHALLENGE_TIMEZONE", "Asia/Kolkata")
DAILY_CHALLENGE_PUBLISH_HOUR = int(os.getenv("DAILY_CHALLENGE_PUBLISH_HOUR", "10"))

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")
GROQ_TEXT_MODEL = os.getenv("GROQ_TEXT_MODEL", "openai/gpt-oss-20b")
GROQ_VISION_MODEL = os.getenv("GROQ_VISION_MODEL", "qwen/qwen3.8-27b")

STATICFILES_DIRS = [
    BASE_DIR / "static"
]
AUTH_USER_MODEL = 'users.User'
LOGIN_URL = "student_login"

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# ---------------------------------------------------------------------------
# Media storage
#
# Development (PRODUCTION=False) keeps serving uploads from the local
# filesystem through MEDIA_ROOT/MEDIA_URL. Production MUST use durable,
# private, S3-compatible object storage and never silently falls back to
# Render's ephemeral filesystem: build_storages() fails closed when the
# required variables are missing.
# ---------------------------------------------------------------------------
MEDIA_STORAGE_REQUIRED_VARS = (
    "MEDIA_STORAGE_BUCKET_NAME",
    "MEDIA_STORAGE_ACCESS_KEY_ID",
    "MEDIA_STORAGE_SECRET_ACCESS_KEY",
)

# WhiteNoise serves collected static assets; keep the existing staticfiles
# backend unchanged while configuring the default (media) backend.
_STATICFILES_STORAGE = {
    "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
}


def build_storages(production):
    """Return the Django ``STORAGES`` mapping for the given mode.

    Production selects an S3-compatible, provider-neutral object-storage
    backend whose objects stay private and are exposed only through
    short-lived signed URLs. Any missing required variable raises
    ``ImproperlyConfigured`` so a misconfigured deployment cannot appear
    healthy while writing uploads to ephemeral local storage.
    """
    if not production:
        return {
            "default": {
                "BACKEND": "django.core.files.storage.FileSystemStorage",
            },
            "staticfiles": dict(_STATICFILES_STORAGE),
        }

    missing = [name for name in MEDIA_STORAGE_REQUIRED_VARS if not os.getenv(name)]
    if missing:
        raise ImproperlyConfigured(
            "Missing production media storage variables: " + ", ".join(missing)
        )

    options = {
        "bucket_name": os.environ["MEDIA_STORAGE_BUCKET_NAME"],
        "access_key": os.environ["MEDIA_STORAGE_ACCESS_KEY_ID"],
        "secret_key": os.environ["MEDIA_STORAGE_SECRET_ACCESS_KEY"],
        # Objects stay private; url() returns short-lived signed links.
        "querystring_auth": True,
        "default_acl": None,
        "file_overwrite": False,
        "querystring_expire": int(os.getenv("MEDIA_STORAGE_QUERYSTRING_EXPIRE", "3600")),
    }
    if os.getenv("MEDIA_STORAGE_ENDPOINT_URL"):
        options["endpoint_url"] = os.environ["MEDIA_STORAGE_ENDPOINT_URL"]
    if os.getenv("MEDIA_STORAGE_REGION_NAME"):
        options["region_name"] = os.environ["MEDIA_STORAGE_REGION_NAME"]
    if os.getenv("MEDIA_STORAGE_ADDRESSING_STYLE"):
        options["addressing_style"] = os.environ["MEDIA_STORAGE_ADDRESSING_STYLE"]

    return {
        "default": {
            "BACKEND": "storages.backends.s3.S3Storage",
            "OPTIONS": options,
        },
        "staticfiles": dict(_STATICFILES_STORAGE),
    }


STORAGES = build_storages(PRODUCTION)

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
DATA_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("DATA_UPLOAD_MAX_MEMORY_SIZE", str(10 * 1024 * 1024)))
FILE_UPLOAD_MAX_MEMORY_SIZE = int(os.getenv("FILE_UPLOAD_MAX_MEMORY_SIZE", str(5 * 1024 * 1024)))

# Brevo's HTTPS API is preferred when its credentials are configured. SMTP and
# console remain available for local development and tests.
BREVO_API_KEY = os.getenv("BREVO_API_KEY", "")
BREVO_SENDER_EMAIL = os.getenv("BREVO_SENDER_EMAIL", "")
BREVO_SENDER_NAME = os.getenv("BREVO_SENDER_NAME", "")
BREVO_API_TIMEOUT = float(os.getenv("BREVO_API_TIMEOUT", "10"))
BREVO_API_CONFIGURED = bool(BREVO_API_KEY and BREVO_SENDER_EMAIL and BREVO_SENDER_NAME)

EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "30"))


def choose_email_backend(*, production, override="", brevo_configured=False, smtp_configured=False):
    """Select the Django email backend.

    Brevo is preferred, then configured SMTP, then console for local
    development. Production must never silently fall back to console
    delivery: an OTP written only to the server logs would look successfully
    sent to the user while never reaching their inbox. Production therefore
    fails closed unless Brevo/SMTP is configured or EMAIL_BACKEND is set.
    """
    if override:
        return override
    if brevo_configured:
        return "accounts.email_backends.BrevoEmailBackend"
    if smtp_configured:
        return "django.core.mail.backends.smtp.EmailBackend"
    if production:
        raise ImproperlyConfigured(
            "Production email is not configured: set BREVO_API_KEY, "
            "BREVO_SENDER_EMAIL and BREVO_SENDER_NAME (or complete SMTP "
            "credentials), or set EMAIL_BACKEND explicitly."
        )
    return "django.core.mail.backends.console.EmailBackend"


EMAIL_BACKEND = choose_email_backend(
    production=PRODUCTION,
    override=os.getenv("EMAIL_BACKEND", ""),
    brevo_configured=BREVO_API_CONFIGURED,
    smtp_configured=bool(EMAIL_HOST_USER and EMAIL_HOST_PASSWORD),
)
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    BREVO_SENDER_EMAIL or EMAIL_HOST_USER or "noreply@kodehaxacademy.local",
)
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24
CSRF_TRUSTED_ORIGINS = _env_list("CSRF_TRUSTED_ORIGINS")
if not PRODUCTION:
    CSRF_TRUSTED_ORIGINS.extend([
        "https://*.ngrok-free.dev",
        "https://*.ngrok-free.app",
    ])

# Render terminates HTTPS and supplies this trusted proxy header.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_REDIRECT_EXEMPT = [r"^health/$"]

SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", PRODUCTION)
SESSION_COOKIE_SECURE = _env_bool("SESSION_COOKIE_SECURE", PRODUCTION)
CSRF_COOKIE_SECURE = _env_bool("CSRF_COOKIE_SECURE", PRODUCTION)
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000" if PRODUCTION else "0"))
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", PRODUCTION)
SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", PRODUCTION)
SECURE_REFERRER_POLICY = os.getenv("SECURE_REFERRER_POLICY", "same-origin")

# Production coding jobs require a separately isolated HTTPS execution service.
# The local backend is a development mitigation, never a public sandbox.
CODE_EXECUTION_BACKEND = os.getenv("CODE_EXECUTION_BACKEND", "remote" if PRODUCTION else "development")
CODE_EXECUTION_URL = os.getenv("CODE_EXECUTION_URL", "")
CODE_EXECUTION_TOKEN = os.getenv("CODE_EXECUTION_TOKEN", "")

from code_execution import checks as execution_checks  # Register deployment readiness checks.
